### ISSUE TITLE
[Suggestion] Commande spécial

### ISSUE THREAD

**Issue by Cleboost** [Youritch/bot_discordv14#5]
Ajouter trois commandes de base,

1. Commande qui envoie un boutons
2. Commande qui envoie un menu déroulant
3. Commande qui envoie un modal

Donner aussi un fichier d'évènement pour chacun de ces exemples.

Ces commandes servirais d'exemple pour ouvrir les interaction spécial.

**Comment by Youritch** [comment]
c'est bon c'est fait
